Rework redis config
claranet/ansible-role-redis pull request #14
Opened 2024-01-17 11:05 UTC by aogereau

## Description
Completely reworked the way redis server configuration is handled .
redis server templates have been reconsolidated into one, and all default values and comments have been removed
Now most of the custom config is handled in a `redis_conf` dictionnary . 
`community.general.redis` module is used to ensure proper configuration is applied . No restarts are needed .
exception for databases parameter as it is immutable and can't be changed via redis-cli, modifying it will require a restart
added additionnal testing cases for custom config and use of password

## Motivation and Context
Changing configuration would require a restart of redis .
Sentinel config rewrite could interfere, resulting in misapplied configuration
Also a lot of parameters weren't handled properly, which required additionnal commits

## How Has This Been Tested?
Molecule

## Screenshots (if appropriate):

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-01-17 14:16 UTC, ElieDeloumeau requested changes
Thank you for this usefull PR!

There are a few small changes to do before merging

2024-01-17 14:16 UTC, ElieDeloumeau commented on vars/main.yml
> +_redis_conf_final: "{{ redis_conf_default |combine(redis_conf) | dict2items | rejectattr('value', 'equalto', '') | list | items2dict }}"
```suggestion
_redis_conf_final: "{{ redis_conf_default | combine(redis_conf) | dict2items | rejectattr('value', 'equalto', '') | list | items2dict }}"
```

2024-01-17 14:16 UTC, ElieDeloumeau commented on tasks/server.yml
> +    login_host: 127.0.0.1
`login_host` should be overridable or take care of `_redis_conf_final.bind`

2024-01-17 14:16 UTC, ElieDeloumeau commented on molecule/password/tests/test_default.py
> +    assert host.socket("tcp://0.0.0.0:6379").is_listening
Please add a test to check if the password is configured

2024-03-14 10:14 UTC, aogereau commented
added rework for Sentinel

2024-03-22 10:25 UTC, ElieDeloumeau approved these changes

2024-03-22 10:26 UTC, merged